import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

test("first Accepted artwork, persistent draw, double challenge and mobile rewards", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/login");
  await page.getByLabel("用户名").fill("e2e-reward-student");
  await page.getByLabel("密码").fill("e2e-reward-password");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page).toHaveURL(/\/student$/);
  await page.evaluate(() => { localStorage.setItem("oj-code-problem-110", "A"); localStorage.setItem("oj-code-problem-111", "A"); });
  await page.goto("/student/problems/110");
  await page.getByRole("button", { name: "提交答案", exact: true }).click();
  await expect(page.getByLabel("通过此题提示", { exact: true })).toBeVisible();
  await expect(page.getByRole("dialog", { name: "通过奖励" })).toHaveCount(0);
  await expect(page.getByRole("dialog", { name: "通过奖励" })).toBeVisible();
  await page.getByRole("button", { name: "稍后再说" }).click();
  await page.reload();
  const dialog = page.getByRole("dialog", { name: "通过奖励" });
  await expect(dialog).toBeVisible();
  await page.route("**/api/rewards/*/draw", (route) => route.abort());
  await dialog.getByRole("button", { name: "开始抽奖" }).click();
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(dialog.getByRole("button", { name: "开始抽奖" })).toBeEnabled();
  await page.unroute("**/api/rewards/*/draw");
  await dialog.getByRole("button", { name: "开始抽奖" }).click();
  await expect(dialog.getByText("积分已计入天梯")).toBeVisible();
  await expect(dialog.getByText("接受挑战剩余时间：", { exact: false })).toBeVisible();
  const initial = await page.evaluate(async () => (await fetch("/api/rewards")).json());
  const amount = initial.rewards[0].amount as number;
  expect(amount).toBeGreaterThanOrEqual(1); expect(amount).toBeLessThanOrEqual(10);
  await dialog.getByRole("button", { name: "接受翻倍挑战" }).click();
  await expect(dialog.getByRole("link", { name: "进入挑战题" })).toHaveAttribute("href", "/student/problems/111");
  await mkdir(path.resolve("tmp/rewards-qa"), { recursive: true });
  await page.screenshot({ path: path.resolve("tmp/rewards-qa/desktop-dialog.png"), fullPage: true });
  await dialog.getByRole("button", { name: "稍后再说" }).click();
  await page.goto("/student");
  await expect(page.getByRole("link", { name: "进入挑战题" })).toBeVisible();
  await page.getByRole("link", { name: "进入挑战题" }).click();
  await page.getByRole("button", { name: "提交答案", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "通过奖励" })).toBeVisible();
  await expect(page.getByText(`翻倍挑战成功！已额外获得 ${amount} 积分。`)).toBeVisible();
  await expect(page.getByRole("button", { name: "开始抽奖" })).toBeVisible();
  await page.getByRole("button", { name: "稍后再说" }).click();
  await page.goto("/student/leaderboard");
  await expect(page.getByRole("heading", { name: "天梯竞技场" })).toBeVisible();
  await expect(page.locator("#my-rewards")).toHaveCount(0);
  const rewardsNav = page.getByRole("link", { name: "我的奖励", exact: true });
  await expect(rewardsNav).toHaveAttribute("href", "/student/rewards");
  await rewardsNav.click();
  await expect(page).toHaveURL(/\/student\/rewards$/);
  await expect(page.getByText(`累计奖励 ${amount * 2} 分`, { exact: false })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "我的奖励" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: path.resolve("tmp/rewards-qa/mobile-leaderboard.png"), fullPage: true });

  const admin = await browser.newPage();
  await admin.goto("/login");
  await admin.getByLabel("用户名").fill("e2e-admin");
  await admin.getByLabel("密码").fill("e2e-admin-password");
  await admin.getByRole("button", { name: "登录", exact: true }).click();
  await expect(admin).toHaveURL(/\/admin$/);
  await admin.goto("/admin/settings");
  await expect(admin.getByLabel("开启抽奖奖励")).toBeChecked();
  await expect(admin.getByLabel("最低奖励积分")).toHaveValue("1");
  await expect(admin.getByLabel("最高奖励积分")).toHaveValue("10");
  await admin.close();
  expect(errors).toEqual([]);
});

test("offer countdown expires live, accepted challenge has its own deadline and archiving renews the offer", async ({ page, browser }) => {
  test.setTimeout(90_000);
  const db = new PrismaClient({ datasources: { db: { url: `file:${path.resolve("prisma/e2e.db").replaceAll("\\", "/")}` } } });
  const admin = await browser.newPage();
  try {
    await page.goto("/login");
    await page.getByLabel("用户名").fill("e2e-offer-student");
    await page.getByLabel("密码").fill("e2e-offer-password");
    await page.getByRole("button", { name: "登录", exact: true }).click();
    await expect(page).toHaveURL(/\/student$/);
    await page.evaluate(() => localStorage.setItem("oj-code-problem-114", "A"));
    await page.goto("/student/problems/114");
    await page.getByRole("button", { name: "提交答案", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "通过奖励" });
    await expect(dialog).toBeVisible();
    await dialog.getByRole("button", { name: "开始抽奖" }).click();
    await expect(dialog.getByText("接受挑战剩余时间：", { exact: false })).toBeVisible();
    const first = await db.rewardDraw.findFirstOrThrow({ where: { userId: 7, sourceProblemId: 114 } });
    expect(first.offerExpiresAt!.getTime() - first.drawnAt!.getTime()).toBe(86400000);
    await dialog.getByRole("button", { name: "稍后再说" }).click();
    await page.goto("/student/rewards");
    await db.rewardDraw.update({ where: { id: first.id }, data: { offerExpiresAt: new Date(Date.now() + 8000) } });
    // Deliberately skew the browser wall clock: the countdown must use server time.
    await page.clock.install({ time: new Date(Date.now() + 3 * 86400000) });
    await page.reload();
    const firstCard = page.locator("#my-rewards article").filter({ hasText: "E2E 奖励题 114" });
    await expect(firstCard.getByRole("button", { name: "接受翻倍挑战" })).toBeVisible();
    await expect(firstCard.getByText("翻倍机会已过期，原奖励积分保留")).toBeVisible({ timeout: 12000 });
    await expect(firstCard.getByRole("button", { name: "接受翻倍挑战" })).toHaveCount(0);
    const origin = new URL(page.url()).origin;
    const expired = await page.request.post(`/api/rewards/${first.id}/challenge`, { headers: { origin } });
    expect(expired.status()).toBe(409);
    expect((await db.pointReward.aggregate({ where: { userId: 7 }, _sum: { amount: true } }))._sum.amount).toBe(first.amount);

    const submission = await page.request.post("/api/problems/115/submit", { headers: { origin }, data: { code: "A" } });
    expect(submission.ok()).toBe(true);
    const secondId = (await submission.json()).rewards.rewardId as number;
    expect((await page.request.post(`/api/rewards/${secondId}/draw`, { headers: { origin } })).ok()).toBe(true);
    await page.reload();
    const secondCard = page.locator("#my-rewards article").filter({ hasText: "E2E 奖励题 115" });
    await secondCard.getByRole("button", { name: "接受翻倍挑战" }).click();
    await expect(secondCard.getByRole("link", { name: "进入挑战题" })).toHaveAttribute("href", "/student/problems/116");
    const challenge = await db.rewardChallenge.findFirstOrThrow({ where: { rewardId: secondId } });
    expect(challenge.expiresAt.getTime() - challenge.acceptedAt.getTime()).toBe(86400000);
    await db.rewardDraw.update({ where: { id: secondId }, data: { offerExpiresAt: new Date(Date.now() - 1000) } });
    await page.reload();
    await expect(secondCard.getByRole("link", { name: "进入挑战题" })).toBeVisible();
    expect((await page.request.post(`/api/rewards/${secondId}/challenge`, { headers: { origin } })).ok()).toBe(true);
    expect(await db.rewardChallenge.count({ where: { rewardId: secondId } })).toBe(1);

    await admin.goto("/login");
    await admin.getByLabel("用户名").fill("e2e-admin");
    await admin.getByLabel("密码").fill("e2e-admin-password");
    await admin.getByRole("button", { name: "登录", exact: true }).click();
    await expect(admin).toHaveURL(/\/admin$/);
    expect((await admin.request.delete("/api/admin/problems/116", { headers: { origin } })).ok()).toBe(true);
    const target = await db.problem.findUniqueOrThrow({ where: { id: 116 } });
    const renewed = await db.rewardDraw.findUniqueOrThrow({ where: { id: secondId } });
    expect(renewed.offerExpiresAt!.getTime()).toBe(target.archivedAt!.getTime() + 86400000);
    await page.reload();
    await expect(secondCard.getByText("原挑战题已下架", { exact: false })).toBeVisible();
    await expect(secondCard.getByText("接受挑战剩余时间：", { exact: false })).toBeVisible();
    await secondCard.getByRole("button", { name: "接受翻倍挑战" }).click();
    await expect(secondCard.getByRole("alert")).toContainText("倒计时不会暂停");
    expect((await db.rewardDraw.findUniqueOrThrow({ where: { id: secondId } })).offerExpiresAt).toEqual(renewed.offerExpiresAt);
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await mkdir(path.resolve("tmp/rewards-qa"), { recursive: true });
    await page.screenshot({ path: path.resolve("tmp/rewards-qa/offer-expiry-mobile.png"), fullPage: true });
  } finally { await db.$disconnect(); await admin.close(); }
});
